version: "3.0"
services:
  mongo:
    image: mongo
    ports:
      - "${HOST_PORT1:-27017}:27017"
    volumes:
      - "./src/test/resources/data:/docker-entrypoint-initdb.d"
  job-mock:
    image: mockserver/mockserver
    ports:
      - "${HOST_PORT2:-1080}:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - "./src/test/resources/data/init.json:/config/init.json"

  job-seeker-service:
    build: .
    image: job-seeker-service
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
