version: "3.0"
services:
  mongo:
    image: mongo
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
  
  job-service:
    build: ../job_sphere
    image: deepjyot/job_sphere
    deploy:
      replicas: 2
    depends_on:
      - mongo
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/job"
  
  candidate-service:
    build: ../job-seeker-service
    image: deepjyot/job-seeker-service
    deploy:
      replicas: 2
    depends_on:
      - mongo
      - job-service
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
      job.service.url: "http://job-service:8080/job/"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./html/index.html:/usr/share/nginx/html/index.html"

    depends_on:
      - job-service
      - candidate-service